#NOTE: Make sure that Docker is running in the background!!!!!
FROM node:lts-alpine
# establish a new root folder. This overrides the default root folder
# The real reason we do this is because it is otherwise possible that a local name might coincide with a similar name in the default root temp container, and overwrite it.
# so instead, we create our own default root directory to copy to. (could be '/foo') creates it if not already exists.
# From this point on, this WORKDIR becomes the default root directory indicated by the second dot.
WORKDIR '/app'
# copy package.json to the temporary container (used as part of the image building process). npm install will find package.json in the temp container, and will create a node_modules folder there
# There will also be a node_modules folder in our local folder. We don't need it. So we will delete the local node_modules folder because it is huge.
# see Volumes.png for discussion about ramifications
COPY package.json .
RUN npm install
# copy everything else (i.e. any local files and folders, to the temp container root folder) 
# These local files and folders are apt to change frequently, so, prevents re-loading of all the above by doing the Copy last from here.
# If you execute this Dockerfile from the command line, and you want volumes behavior, you need to format the docker instruction accordingly. a royal pain. So that is why we use docker-compose to set up volumes
# Also, the port mapping is being done in the docker-copmpse file - "3000:3000"
# Copy instruction is moot now because if you use volumes. Dockerfile.dev will still work without COPY because of what we did in docker-compose with volumes. We only need this if doing docker build at terminal
COPY . .
# Default start command, will start up a development server. So that is why this is not a good thing for a production environment.
# Instead, for the production version, we will use Nginx as the web server for production, and there will not be any startup default commands mentioned in the Dockerfile for production
CMD ["npm", "run", "start"]